[package]
name = "longest_collatz"
version = "0.1.0"
authors = ["roy <roy.crippen@archarithms.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.3.1"
